
# PROBLEMS

## **Problem-#1** - `initialise_collections` in `registrar`

There seems to be a race-condition during startup - when `resource-catalogue` and `data-access` are deployed from clean all at once. After initial deployment the collections have not been recreated and there are errors in the registrar log. The remedy is to then delete the `registrar` pod - forcing it to be recreated - and then the `initialise-collections` is successful.

## **Problem-#2** - WMS service

There seems to be a problem with WMS service on the `develop` cluster, but not on the `demo` cluster.

The problem is the GetMap request which simply times-out - and can be demonstrated with both the `05 Data Access` Jupyter notebook, and with QGIS - both of which work fine with the `demo` cluster.

This is the [request generated by QGIS](https://data-access.develop.eoepca.org/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=1815830.94197272067,5914797.41638581641,1981803.827413877472,6081259.759856631979&CRS=EPSG:3857&WIDTH=516&HEIGHT=519&LAYERS=S2B_MSIL1C_20190910T095029_N0208_R079_T33TXN_20190910T120910.SAFE__TRUE_COLOR&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE) - https://data-access.develop.eoepca.org/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=1815830.94197272067,5914797.41638581641,1981803.827413877472,6081259.759856631979&CRS=EPSG:3857&WIDTH=516&HEIGHT=519&LAYERS=S2B_MSIL1C_20190910T095029_N0208_R079_T33TXN_20190910T120910.SAFE__TRUE_COLOR&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE.

> **Notes:**
> * the problem also occurs in my local cluster that is aligned with the develop cluster (same image tags etc.) - so maybe recent data-access updates are to blame
> * the problem does **not** occur with the `__outlines` layer.
